#!/usr/bin/env python3
"""Fixture test for OKR_BANDS and okr_score() (21/09/2026).

WHY THIS TEST EXISTS AT ALL. Ross agreed banded scoring on 21/09/2026, which
replaced the scorecard's old "green when the target is met, red when it is not,
and no amber because nobody agreed a tolerance" rule. The bands ARE the
judgement now, so a wrong threshold is not a cosmetic bug - it is the whole
page being wrong about whether the business hit its targets, in a document
Ross is reviewed against.

WHAT IT CHECKS, AND WHY IT IS SHAPED LIKE THIS. Every boundary of every band,
from BOTH sides. A band is a set of edges, and every bug a band can have lives
on an edge: >= written as >, a threshold off by one, two rows in the wrong
order. Testing 93.5 and 93.0 tells you more than testing 50 and 99.

The cautionary tale is in the source sheet. Matthew's OO2 KR4 efficiency
formula is =IF(I>=0,100,IF(AND(I<=0,I>=-1),80,IF(AND(I<-1.9,I>=-2.5),50,0))),
which leaves a DEAD BAND for roughly -1.9 < I < -1.0: it scores 93.5 as 0 while
scoring a WORSE 93.0 as 50. Nobody noticed because nobody tested the edges. The
monotonicity test at the bottom of this file is there to make that class of bug
impossible here: for every band, a better value may never score worse.

Run: python3 tests/okr_bands_test.py    (exits non-zero on any failure)
"""

from __future__ import annotations

import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BAKE = os.path.join(HERE, "..", "builders", "bake_ops_command.py")

_spec = importlib.util.spec_from_file_location("bake", BAKE)
bake = importlib.util.module_from_spec(_spec)
try:
    _spec.loader.exec_module(bake)
except SystemExit:
    pass

FAILURES: list[str] = []


def eq(got, want, what: str) -> None:
    if got != want:
        FAILURES.append(f"{what}: got {got!r}, expected {want!r}")


#: (band, value, expected score). Every threshold in the table, plus the value
#: immediately either side of it, plus a clear pass and a clear fail. The
#: expectations are written out by hand from the band table Ross agreed - NOT
#: generated from OKR_BANDS, which would only prove the code agrees with itself.
CASES = [
    # pct95: >=95 -> 100; >=90 -> 80; >=85 -> 50; else 0
    ("pct95", 100, 100), ("pct95", 95, 100), ("pct95", 94.9, 80),
    ("pct95", 90, 80), ("pct95", 89.9, 50), ("pct95", 85, 50),
    ("pct95", 84.9, 0), ("pct95", 0, 0),
    # repeat: change vs baseline <=-20 -> 100; <=-10 -> 80; <=0 -> 50; else 0
    ("repeat", -35, 100), ("repeat", -20, 100), ("repeat", -19.9, 80),
    ("repeat", -10, 80), ("repeat", -9.9, 50), ("repeat", 0, 50),
    ("repeat", 0.1, 0), ("repeat", 15, 0),
    # zero: 0 -> 100; 1 -> 80; 2-3 -> 50; >=4 -> 0
    ("zero", 0, 100), ("zero", 1, 80), ("zero", 2, 50), ("zero", 3, 50),
    ("zero", 4, 0), ("zero", 11, 0),
    # zero_strict: 0 -> 100; 1 -> 50; >=2 -> 0   (no 80 band on this one)
    ("zero_strict", 0, 100), ("zero_strict", 1, 50), ("zero_strict", 2, 0),
    ("zero_strict", 9, 0),
    # full: 100 -> 100; >=99 -> 80; >=98 -> 50; else 0
    ("full", 100, 100), ("full", 99.9, 80), ("full", 99, 80),
    ("full", 98.9, 50), ("full", 98, 50), ("full", 97.9, 0), ("full", 0, 0),
    # contact: 100 -> 100; >=95 -> 80; >=90 -> 50; else 0
    ("contact", 100, 100), ("contact", 99.9, 80), ("contact", 95, 80),
    ("contact", 94.9, 50), ("contact", 90, 50), ("contact", 89.9, 0),
    # issues: <=10 -> 100; <=20 -> 80; <=40 -> 50; else 0   (Ross, 21/09/2026)
    ("issues", 0, 100), ("issues", 10, 100), ("issues", 11, 80),
    ("issues", 20, 80), ("issues", 21, 50), ("issues", 40, 50),
    ("issues", 41, 0), ("issues", 78, 0),
    # spikes: <=3 -> 100; 4 -> 80; 5 -> 50; >=6 -> 0
    ("spikes", 0, 100), ("spikes", 3, 100), ("spikes", 4, 80),
    ("spikes", 5, 50), ("spikes", 6, 0), ("spikes", 115, 0),
    # audit: generated by the 3rd -> 100; by the 10th -> 50; else 0
    ("audit", 1, 100), ("audit", 3, 100), ("audit", 4, 50),
    ("audit", 10, 50), ("audit", 11, 0), ("audit", 28, 0),
    # damaged: <=5 -> 100; 6-7 -> 80; 8-10 -> 50; >=11 -> 0
    ("damaged", 0, 100), ("damaged", 5, 100), ("damaged", 6, 80),
    ("damaged", 7, 80), ("damaged", 8, 50), ("damaged", 10, 50),
    ("damaged", 11, 0), ("damaged", 40, 0),
    # density: INPUT IS THE DISTANCE OUTSIDE THE BAND, not the mean.
    # inside -> 100; <=0.5 outside -> 80; <=1.0 outside -> 50; else 0
    ("density", 0, 100), ("density", 0.5, 80), ("density", 0.51, 50),
    ("density", 1.0, 50), ("density", 1.01, 0), ("density", 4, 0),
    # stock: abs variance <=5 -> 100; <=7.5 -> 80; <=10 -> 50; else 0
    ("stock", 0, 100), ("stock", 5, 100), ("stock", 5.1, 80),
    ("stock", 7.5, 80), ("stock", 7.6, 50), ("stock", 10, 50),
    ("stock", 10.1, 0), ("stock", 77.3, 0),
    # comp: >=95 -> 100; >=94 -> 80; >=92.5 -> 50; else 0
    ("comp", 100, 100), ("comp", 95, 100), ("comp", 94.9, 80),
    ("comp", 94, 80), ("comp", 93.9, 50), ("comp", 92.5, 50),
    ("comp", 92.4, 0), ("comp", 0, 0),
    # prod: >=98 -> 100; >=97 -> 80; >=95 -> 50; else 0
    ("prod", 100, 100), ("prod", 98, 100), ("prod", 97.9, 80),
    ("prod", 97, 80), ("prod", 96.9, 50), ("prod", 95, 50),
    ("prod", 94.9, 0), ("prod", 66.7, 0),
]

for band, value, want in CASES:
    eq(bake.okr_score(band, value), want, f"okr_score({band!r}, {value})")

# ---- rule 3 survives banding: no value, no score -------------------------
# A KR with nothing to measure did not score zero. This is the distinction the
# whole scorecard rests on - "nobody measured this" and "this failed" must
# never render alike - and it is one `or` away from being broken.
for band in bake.OKR_BANDS:
    eq(bake.okr_score(band, None), None, f"okr_score({band!r}, None)")
eq(bake.okr_score(None, 95), None, "okr_score(None, 95)")
eq(bake.okr_score("no_such_band", 95), None, "okr_score('no_such_band', 95)")
# 0 IS A REAL VALUE, not a missing one. Three bands score 0 as a perfect 100.
eq(bake.okr_score("zero", 0), 100, "okr_score('zero', 0) - zero is a value")
eq(bake.okr_score("density", 0), 100, "okr_score('density', 0)")

# ---- the table itself -----------------------------------------------------
eq(sorted(bake.OKR_BANDS), sorted(bake.OKR_BAND_STATUS),
   "every band has a band_status")
eq(sorted({v for v in bake.OKR_BAND_STATUS.values()}), ["agreed", "proposed"],
   "band_status values")
#: The five Ross has NOT signed off (21/09/2026). They score like any other
#: band; the difference is that the row wears a PROPOSED chip until Matthew
#: confirms them. If this list shrinks, it is because he confirmed one - and
#: that should be a deliberate edit, not a drift.
eq(sorted(k for k, v in bake.OKR_BAND_STATUS.items() if v == "proposed"),
   ["audit", "damaged", "density", "repeat", "stock"],
   "the bands still marked PROPOSED")
eq(bake.OKR_RAG, {100: "green", 80: "amber", 50: "amber", 0: "red"},
   "RAG follows the score")

# ---- MONOTONICITY: a better value may never score worse -------------------
# This is the test that would have caught the sheet's own broken formula.
for band, (direction, table) in bake.OKR_BANDS.items():
    thresholds = [t for t, _ in table]
    probes = sorted({p for t in thresholds
                     for p in (t - 1, t - 0.1, t, t + 0.1, t + 1)})
    scores = [bake.okr_score(band, p) for p in probes]
    if direction == "ge":
        # higher is better, so scores must never decrease as the value rises
        pairs = list(zip(scores, scores[1:]))
        bad = [(probes[i], probes[i + 1], a, b)
               for i, (a, b) in enumerate(pairs) if a > b]
    else:
        # lower is better, so scores must never increase as the value rises
        pairs = list(zip(scores, scores[1:]))
        bad = [(probes[i], probes[i + 1], a, b)
               for i, (a, b) in enumerate(pairs) if a < b]
    if bad:
        v1, v2, s1, s2 = bad[0]
        FAILURES.append(
            f"band {band!r} is NON-MONOTONIC ({direction}): {v1} scores {s1} "
            f"but {v2} scores {s2}. This is the exact bug in the source "
            f"sheet's OO2 KR4 formula - a dead band between two thresholds")

# ---- okr_density_outside --------------------------------------------------
# The bridge between a broth mean and the `density` band. Bounds are INCLUSIVE,
# matching FACTORY_BROTH_BANDS, so a reading exactly on 8.0 or 9.0 is in band.
TONKOTSU, CHICKEN = (8.0, 9.0), (5.0, 6.0)
eq(bake.okr_density_outside(8.35, TONKOTSU), 0.0, "tonkotsu 8.35 is in band")
eq(bake.okr_density_outside(8.0, TONKOTSU), 0.0, "tonkotsu 8.0 (lower bound)")
eq(bake.okr_density_outside(9.0, TONKOTSU), 0.0, "tonkotsu 9.0 (upper bound)")
eq(bake.okr_density_outside(7.6, TONKOTSU), 0.4, "tonkotsu 7.6 is 0.4 low")
eq(bake.okr_density_outside(9.7, TONKOTSU), 0.7, "tonkotsu 9.7 is 0.7 high")
eq(bake.okr_density_outside(5.34, CHICKEN), 0.0, "chicken 5.34 is in band")
eq(bake.okr_density_outside(None, TONKOTSU), None, "no mean, no distance")
eq(bake.okr_density_outside(8.35, None), None, "no band, no distance")

# The real 2026 means, from the live feed. EVERY ONE SCORES 100, which is the
# point of recording them here: the mean on its own cannot fail this KR. April
# chicken is the sharpest case - only 77.3% of its readings were in band, and
# the mean still sits dead centre, because a symmetric spread of misses cancels
# out. If Ross ever moves the SCORE onto the in-band percentage, this block is
# what should change, and it should change loudly.
REAL_2026 = [
    ("Tonkotsu", TONKOTSU, [8.38, 8.31, 8.30, 8.38, 8.37, 8.35, 8.25, 8.35, 8.40]),
    ("Chicken", CHICKEN, [5.09, 5.04, 5.16, 5.10, 5.30, 5.06, 5.13, 5.34, 5.19]),
]
for name, band, means in REAL_2026:
    for mean in means:
        out = bake.okr_density_outside(mean, band)
        eq(bake.okr_score("density", out), 100,
           f"{name} monthly mean {mean} scores 100 (mean cannot fail)")

# ---- the thirty KRs -------------------------------------------------------
eq(len(bake.OKR_SPEC), 30, "thirty KRs")
eq(len(bake.OKR_OBJECTIVES), 6, "six objectives")
_per = {}
for obj, kr, text, owner, target, band in bake.OKR_SPEC:
    _per[obj] = _per.get(obj, 0) + 1
eq(sorted(_per.items()), [("OO1", 5), ("OO2", 5), ("OO3", 5), ("OO4", 5),
                          ("OO5", 5), ("OO6", 5)], "five KRs per objective")
eq([o for o, _ in bake.OKR_OBJECTIVES],
   ["OO1", "OO2", "OO3", "OO4", "OO5", "OO6"], "objectives in sheet order")
eq(bake.OKR_OPERATIONS_OBJECTIVES, ("OO2", "OO3", "OO4", "OO5", "OO6"),
   "OO1 is excluded from the Operations percentage - it is Finance's")
# Every band a KR names must exist, or a row would carry a score from nowhere.
_unknown = sorted({b for *_r, b in bake.OKR_SPEC if b and b not in bake.OKR_BANDS})
eq(_unknown, [], "every band named by a KR exists in OKR_BANDS")
# OO1 carries no band: it is read from the sheet already scored, never computed.
eq([b for o, _k, _t, _o, _tg, b in bake.OKR_SPEC if o == "OO1"], [None] * 5,
   "OO1 KRs carry no band")
eq([o for _ob, _k, _t, o, _tg, _b in bake.OKR_SPEC if _ob == "OO1"],
   ["Finance"] * 5, "OO1 is Finance-owned")
# The sheet's own wording, kept verbatim - including its inconsistent prefixes.
# If somebody "tidies" these, the scorecard and the sheet stop matching and two
# people start disagreeing about which KR is which in a review.
_texts = {(o, k): t for o, k, t, _o, _tg, _b in bake.OKR_SPEC}
eq(_texts[("OO3", "KR1")], "KR 1: Minimise delivery issues with suppliers",
   "OO3 KR1 keeps the sheet's 'KR 1:' spacing")
eq(_texts[("OO3", "KR2")], "KR2 : Price change spike (3 items)",
   "OO3 KR2 keeps the sheet's 'KR2 :' spacing")
eq(_texts[("OO4", "KR4")],
   "KR: 100% of delivery credit notes and refunds actioned through MAPAL and Finance",
   "OO4 KR4 keeps the sheet's 'KR:' (the sheet omits the number)")
eq(_texts[("OO6", "KR3")],
   "KR3: Live inventory of all forzen ramen and all locations",
   "OO6 KR3 keeps the sheet's misspelling of 'frozen'")
eq(_texts[("OO6", "KR5")],
   "KR5: Seperation of Invoices associated with Frozen Ramen at Factory Level",
   "OO6 KR5 keeps the sheet's misspelling of 'Separation'")

# ---- every KR with no source names the phase that will give it one --------
_pending_ids = set(bake.OKR_PENDING)
_spec_ids = {(o, k) for o, k, *_ in bake.OKR_SPEC}
eq(sorted(_pending_ids - _spec_ids), [], "OKR_PENDING names no KR that does not exist")

if FAILURES:
    print(f"FAIL ({len(FAILURES)}):")
    for f in FAILURES:
        print("  -", f)
    sys.exit(1)
print(f"okr_bands_test: OK ({len(CASES)} band boundaries + monotonicity over "
      f"{len(bake.OKR_BANDS)} bands + {len(bake.OKR_SPEC)} KR specs)")
